### ISSUE TITLE
 oAuth error

### ISSUE THREAD

**Issue by pimbolilu** [crohrer/spotifyRadioPlaylist#4]
Hello,

I get the following error:

no accessToken found

/Users/sven/spotifyRadioPlaylist/spotifyOAuth.js:50
            oAuth.refresh();
            ^
ReferenceError: oAuth is not defined

can you help me how to solve this.

br,
pim.

**Comment by crohrer** [comment]
Should work now. Thanks for reporting!

**Comment by chrisheinzelmann** [comment]
Should work now. Thanks for reporting!
